version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: affiliate_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  app:
    build: .
    environment:
      - DB_DSN=appuser:apppass@tcp(db:3306)/affiliate_db?parseTime=true&charset=utf8mb4
      - PORT=8080
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data: